### ISSUE TITLE
Rails 5 Pre - ActionDispatch::Session::RedisStore (NameError)

### ISSUE THREAD

**Issue by ziyan-junaideen** [redis-store/redis-rails#40]
I am getting an error in Rails 5 pre and setting up Redis Rails. I have used Redis rails with Rails 4.x, I assume this is because I am using Rails 5 pre?

Any suggestions on the following error...

It reads... 

````
=> Run `rails server -h` for more startup options
Exiting
/home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/application/configuration.rb:180:in `const_get': uninitiali$
ed constant ActionDispatch::Session::RedisStore (NameError)
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/application/configuration.rb:180:in `session_s$
ore'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/application/default_middleware_stack.rb:58:in $
block in build_stack'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/application/default_middleware_stack.rb:13:in $
tap'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/application/default_middleware_stack.rb:13:in $
build_stack'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/application.rb:504:in `default_middleware_stac$
'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/engine.rb:506:in `block in app'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/engine.rb:504:in `synchronize'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/engine.rb:504:in `app'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/application/finisher.rb:34:in `block in <modul$
:Finisher>'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:30:in `run'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:55:in `block in run_initialize
rs'
        from /home/ziyan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /home/ziyan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/ziyan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/ziyan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/ziyan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /home/ziyan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /home/ziyan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/ziyan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /home/ziyan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/railties-5.0.0.rc1/lib/rails/application.rb:352:in `initialize!'
        from /home/ziyan/Work/JDeen/tmp/config/environment.rb:5:in `<top (required)>'
        from /home/ziyan/Work/JDeen/tmp/config.ru:3:in `require_relative'
        from /home/ziyan/Work/JDeen/tmp/config.ru:3:in `block in <main>'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/rack-2.0.0.rc1/lib/rack/builder.rb:55:in `instance_eval'
        from /home/ziyan/.rvm/gems/ruby-2.3.0@lanka_internet_website/gems/rack-2.0.0.rc1/lib/rack/builder.rb:55:in `initialize'
        from /home/ziyan/Work/JDeen/tmp/config.ru:in `new'
````

**Comment by ziyan-junaideen** [comment]
Silly me, I didn't pull the master branch. Very sorry, my bad, seems to work.

**Comment by tubbo** [comment]
no worries @ziyan-junaideen, we also have version `5.0.0.pre` up on rubygems.org if you aren't into building against a "moving target". it was released a few weeks ago, but i think you have to specify it explicitly in your Gemfile.
