### ISSUE TITLE
Can not `read` key created by `increment`

### ISSUE THREAD

**Issue by fguillen** [redis-store/redis-rails#73]
```
$ rails c -e staging
Loading staging environment (Rails 5.0.2)
irb(main):001:0> Rails.cache.increment "test10", 1
=> 1
irb(main):002:0> Rails.cache.increment "test10", 1
=> 2
irb(main):003:0> Rails.cache.increment "test10", 1
=> 3
irb(main):004:0> Rails.cache.read "test10"
ArgumentError: marshal data too short
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/marshal.rb:4:in `load'
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/core_ext/marshal.rb:4:in `load'
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-store-1.3.0/lib/redis/store/marshalling.rb:43:in `_unmarshal'
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-store-1.3.0/lib/redis/store/marshalling.rb:17:in `get'
```

Let me know if you need more information

**Comment by fguillen** [comment]
I have also problems to `write` the key and then try to `increment` it:

```
Loading staging environment (Rails 5.0.2)
irb(main):001:0> Rails.cache.write "test12", 1
=> "OK"
irb(main):002:0> Rails.cache.read "test12"
=> 1
irb(main):003:0> Rails.cache.increment "test12"
Redis::CommandError: ERR value is not an integer or out of range
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:121:in `call'
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:706:in `block in incrby'
	from /Users/fguillen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
```

**Comment by fguillen** [comment]
My fault, I should use `:raw => false` as a option:

    Rails.cache.read "test", { :raw => true }
