### ISSUE TITLE
Is it possible to store session data as json in redis?

### ISSUE THREAD

**Issue by elvis-tang** [redis-store/redis-rails#75]
I've tried using the following config, However it seems to be not right. 

```ruby
MyApplication::Application.config.session_store :redis_store, {
  servers: [redis_url] ,
  key: "#{Rails.env}_session",
  expires_in: 10.days,
  serializer: JSON
}
```

**Comment by tl3shi** [comment]
@tubbo Hope for your help.

**Comment by tubbo** [comment]
@elvis-tang did you ensure `redis-store` is at 1.4.0?

**Comment by tl3shi** [comment]
@tubbo  I'm sure, it is the newest code. I am using the code by git and all the repos of the group redis-store is the HEAD version of master branch. 

I've tried to change the `initialize` method in `redis/store.rb` to  `@serializer = JSON` manually here [ref](https://github.com/redis-store/redis-store/blob/master/lib/redis/store.rb#L30).

It seems to be wrong for the serialization for `ActiveSupport::Cache::Entry`, the details is as follows: 

```ruby
ompleted 500 Internal Server Error in 317ms (ActiveRecord: 25.5ms | Elasticsearch: 0.0ms)

JSON::ParserError - 795: unexpected token at o: ActiveSupport::Cache::Entr:
                                                                           @valueo:5Badge::ActiveRecord_Associations_CollectionProxy
                                :@associationU::ActiveRecord::Associations::HasManyThroughAssociation[:
   badges[[:
o:$ActiveRecord::LazyAttributeHashattributeso:ActiveRecord::AttributeSet;
:
 @types}I"id:ETo: ActiveRecord::Type::Integer	:@precision0:
                                                             @scale0:
                                                                     @limiti	:
                                                                                 @rangeo:
Rang:	exclT:
beginl-':
  json (1.8.6) lib/json/common.rb:155:in `parse'
  json (1.8.6) lib/json/common.rb:334:in `load'
   () Users/tanglei/.rvm/gems/ruby-2.2.2/bundler/gems/redis-store-c83c0c5ae630/lib/redis/store/serialization.rb:54:in `_unmarshal'
```

**Comment by tl3shi** [comment]
@tubbo  The fact is that  the configuration is wrong.   The following is OK.

```ruby
MyApplication::Application.config.session_store :redis_store, {
  servers: [{
      host: xxx,
      serializer: JSON
      ......
}] ,
  key: "#{Rails.env}_session",
  expires_in: 10.days
}
```

**Comment by tubbo** [comment]
ahh, ok. thanks for the clarification. I’ll update the README so it’s a little more clear.
