### ISSUE TITLE
uninitialized constant ImagesUploader::Uploader when after switch from memcached to redis

### ISSUE THREAD

**Issue by AndreiMotinga** [redis-store/redis-rails#83]
Hello,

I got rails app that over past month I've updated from rails 3.2 to rails 5.1. It uses Mongoid 6.4
I have Film model that's defined roughly as 

```
class Film
  include Mongoid::Document
  ...
  ...

  mount_uploader :film_poster, ImagesUploader
  mount_uploader :header_marquee, ImagesUploader
  mount_uploader :photo_1, ImagesUploader
  mount_uploader :photo_2, ImagesUploader
  mount_uploader :photo_3, ImagesUploader
  mount_uploader :photo_4, ImagesUploader
  mount_uploader :photo_5, ImagesUploader
  mount_uploader :xomo_img, ImagesUploader

  ... 

  def images
    Rails.cache.fetch([self, :images]) { photos }
  end

  ... 

  private 

  def photos
    imgs = (1..5).map { |i| send("photo_#{i}") }
                 .compact
    imgs.any? ? imgs : [header_marquee].compact
  end
```

and in `root/app/uploaders/images_uploader.rb`

```
# encoding: utf-8
# allows uploaing and processing images
class ImagesUploader < CarrierWave::Uploader::Base

  include CarrierWave::MiniMagick
  include CarrierWave::ImageOptimizer

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  #to use in views, just use model_name.photo.small to render the small version

  # simply add more versions using the following template

  version :small, from_version: :large do
    process :resize_to_fill => [200, 0]
    # can use :resize_to_limit instead of :resize_to_fill if you don't want the
    # image proportions changed
  end

  version :medium, from_version: :large do
    process :resize_to_fill => [400, 0]
  end

  version :large, from_version: :full do
    process :resize_to_fill => [980,0]
  end

  version :full do
    process :resize_to_fill => [1280,0]
  end

  def default_url(*args)
    # ActionController::Base.helpers.asset_path('graphic-no-image.jpg')
  end

    def cache_stored_file!
    _content = file.read
    if _content.is_a?(File) # could be if storage is Fog
      _tempfile = _content.read
    else
      _tempfile = StringIO.new(_content)
    end
    sanitized = SanitizedFile.new :tempfile => _tempfile,
      :filename => File.basename(path), :content_type => file.content_type

    cache! sanitized
  end

  def extension_white_list
    %w(jpg jpeg gif png tiff)
  end

  process :optimize
  process :store_dimensions


  private

    # TODO: Store dimensions based on field name
    def store_dimensions
      if file && model && model.class.attribute_names.include?("image_width")
        model.image_width, model.image_height = ::MiniMagick::Image.open(file.file)[:dimensions]
      end
    end

end
```

when using memcached it works as expected ( at least I think it does ). But after switching to redis-store  I get `uninitialized constant ImagesUploader::Uploader70158775019920`

Application Trace 
```
app/models/film.rb:208:in `images'
app/views/films/show/_header.html.erb:13:in `_app_views_films_show__header_html_erb___52282132443415310_70158628478300'
app/views/films/show.html.slim:11:in `_app_views_films_show_html_slim__3825912085733181100_70158625939000'
```

Framework Trace 
```
activesupport (5.1.5) lib/active_support/inflector/methods.rb:271:in `const_get'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:271:in `block in constantize'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:267:in `each'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:267:in `inject'
activesupport (5.1.5) lib/active_support/inflector/methods.rb:267:in `constantize'
activesupport (5.1.5) lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
activesupport (5.1.5) lib/active_support/core_ext/marshal.rb:8:in `rescue in load'
activesupport (5.1.5) lib/active_support/core_ext/marshal.rb:4:in `load'
redis-store (1.4.1) lib/redis/store/serialization.rb:43:in `_unmarshal'
redis-store (1.4.1) lib/redis/store/serialization.rb:17:in `get'
redis-store (1.4.1) lib/redis/store/namespace.rb:23:in `block in get'
redis-store (1.4.1) lib/redis/store/namespace.rb:88:in `namespace'
redis-store (1.4.1) lib/redis/store/namespace.rb:23:in `get'
redis-activesupport (5.0.4) lib/active_support/cache/redis_store.rb:260:in `block in read_entry'
redis-activesupport (5.0.4) lib/active_support/cache/redis_store.rb:242:in `with'
redis-activesupport (5.0.4) lib/active_support/cache/redis_store.rb:260:in `read_entry'
activesupport (5.1.5) lib/active_support/cache.rb:288:in `block in fetch'
activesupport (5.1.5) lib/active_support/cache.rb:555:in `block in instrument'
activesupport (5.1.5) lib/active_support/notifications.rb:168:in `instrument'
activesupport (5.1.5) lib/active_support/cache.rb:555:in `instrument'
activesupport (5.1.5) lib/active_support/cache.rb:287:in `fetch'
actionview (5.1.5) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.5) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.5) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.5) lib/action_view/template.rb:155:in `render'
rack-mini-profiler (0.10.7) lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.5) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.5) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.5) lib/active_support/notifications.rb:166:in `instrument'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/partial_renderer.rb:310:in `render'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (5.1.5) lib/action_view/helpers/rendering_helper.rb:35:in `render'
actionview (5.1.5) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.5) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.5) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.5) lib/action_view/template.rb:155:in `render'
rack-mini-profiler (0.10.7) lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.5) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.5) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.5) lib/active_support/notifications.rb:166:in `instrument'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/template_renderer.rb:50:in `render_template'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/template_renderer.rb:14:in `render'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/renderer.rb:42:in `render_template'
/usr/local/Cellar/rbenv/1.1.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.1.5/lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.1.5) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.1.5) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.1.5) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.1.5) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.1.5) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (5.1.5) lib/abstract_controller/rendering.rb:24:in `render'
actionpack (5.1.5) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.1.5) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.1.5) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (5.1.5) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.1.5) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.1.5) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
actionpack (5.1.5) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (5.1.5) lib/action_controller/metal/implicit_render.rb:33:in `default_render'
actionpack (5.1.5) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
actionpack (5.1.5) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
actionpack (5.1.5) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.5) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.5) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.5) lib/active_support/callbacks.rb:108:in `block in run_callbacks'
react-rails (2.4.4) lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
activesupport (5.1.5) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
activesupport (5.1.5) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (5.1.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.5) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.5) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.5) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.5) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.5) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
actionpack (5.1.5) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.5) lib/action_view/rendering.rb:30:in `process'
rack-mini-profiler (0.10.7) lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
actionpack (5.1.5) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.5) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.5) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.5) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.5) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.5) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.5) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.5) lib/action_dispatch/routing/route_set.rb:844:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
bullet (5.7.5) lib/bullet/rack.rb:12:in `call'
mongoid (6.4.0) lib/mongoid/query_cache.rb:118:in `block in call'
mongoid (6.4.0) lib/mongoid/query_cache.rb:69:in `cache'
mongoid (6.4.0) lib/mongoid/query_cache.rb:118:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.4) lib/rack/etag.rb:25:in `call'
rack (2.0.4) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.4) lib/rack/head.rb:12:in `call'
rack (2.0.4) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.4) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.5) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.5) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/executor.rb:12:in `call'
rollbar (2.15.5) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
rollbar (2.15.5) lib/rollbar.rb:145:in `scoped'
rollbar (2.15.5) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
rollbar (2.15.5) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.5) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.5) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.5) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.5) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.5) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.5) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.4) lib/rack/method_override.rb:22:in `call'
rack (2.0.4) lib/rack/runtime.rb:22:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.4) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
rack-mini-profiler (0.10.7) lib/mini_profiler/profiler.rb:282:in `call'
railties (5.1.5) lib/rails/engine.rb:522:in `call'
puma (3.11.3) lib/puma/configuration.rb:225:in `call'
puma (3.11.3) lib/puma/server.rb:624:in `handle_request'
puma (3.11.3) lib/puma/server.rb:438:in `process_client'
puma (3.11.3) lib/puma/server.rb:302:in `block in run'
puma (3.11.3) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

![screen shot 2018-03-29 at 3 08 39 pm](https://user-images.githubusercontent.com/6856852/38096744-9ce108c0-3341-11e8-9b7f-2bbf9d248ff5.png)

I understand that issue is most likely with the setup, and not the gem itself, but I figured it worth noting it here.  
Interesting **NOTE**:  if I clear cache with `Rails.cache.clear` page works as expected, but after server restart issue happens again.  I assume it's related to constant not being loaded, or the way things get serialized, or something like that.   I tried playing with auto_load and eager_load, tried requring file, etc. 

I figured you, folks, here, might help to figure this out. 

Thank you.

**Comment by AndreiMotinga** [comment]
@tubbo, yes I read that thread, meant to mention it here, but forgot. 

>  Are you using the built-in MemCacheStore from Rails or something like Dalli?

not sure how to answer that.  in environment/production.rb 
before 
`config.cache_store = :dalli_store, memcached url`
after 
`config.cache_store = :redis_store, redis url`

other than that I don't see it specified anywhere else.

**Comment by tubbo** [comment]
oh ok cool. rails comes with a `:mem_cache_store` by default as well. but if you're using `:dalli_store` and you say it works there, that's pretty strange.

**Comment by AndreiMotinga** [comment]
btw. in film model 

```
  def cached_screenings
    Rails.cache.fetch([self, :screenings]) do
      sc = screenings.present? ? screenings : parent_program_film&.screenings
      sc&.asc(:date)
    end
  end
```

so it seems like cache loads screening model just fine. 
I suppose it's not related to the fact, that uploaders are under  app/uploaders, but the fact that they are `class ImagesUploader < CarrierWave::Uploader::Base`.

**Comment by AndreiMotinga** [comment]
I guess, the bottom line is it's more of a carrierwave-mongoid issue than redis-rails.

**Comment by tubbo** [comment]
hey @AndreiMotinga let me know if you need anything else, but if it's a mongoid issue then i'm just gonna close.
