### ISSUE TITLE
Some sessions not expiring?

### ISSUE THREAD

**Issue by axos88** [redis-store/redis-rails#99]
I have a bunch of sessions in my redis that are not expiring. I am using a seaparate db for the session store, like so (I am not using this db for anything else):
```
Rails.application.config.session_store :redis_store,
  servers: ["#{redis_url}/1/session"],
  expire_after: 90.minutes,
  key: "_#{Rails.application.class.parent_name.downcase}_session",
  threadsafe: false
```

But I keep seeing that some of these keys do not get a TTL:

```
db1:keys=81,expires=1,avg_ttl=2325900
```

```
ec2-52-31-192-111.eu-west-1.compute.amazonaws.com:32649> keys *
1) session:9a5894533a58f1593161484cb09708fb8852807a30f3831b53816c0240a024eb
2) session:ce65f835f59cdee671c793a8f35c51c52d17ab0123a826059399266203b2f9d8
3) session:d90c0cad5dcceacd036eb39358bff766c9ce3b4c4aae2999eff6b6f901c202ab
4) session:9df255c7b7efb91b86eff683bd9a216d54458688693065f37d2ec0cb9462fdad
5) session:ee303d1d979c202cc0cca20257869b10e074a97e7119f454badfd35177c6235e
6) session:005c70201f6f466897b540e35cf130bd027ce411c51e1b2d32d9d9a044428ee4
7) session:f9b6b0ea533cbfef42663ceade1239e0dfa3de580e8dd98c72998eff28b62df0
8) session:16a676d09219fd9d7b08270a653c69ff6e054b5353d7f22b7e73fa246d0f031d
9) session:d8a44abde115de4c8e771b674038eea749031a76fb91112d19cc3a902e9ff735
10) session:b426cf008d9410971746c70e4652a8110c36c6f2379f734d671d5c0f86c0b789
11) session:1340f9e62d00c2c75cfdb4398cad67b17f653ce046b572f5866e191e217c95ee
12) session:47ec6fadab9b082625bd28c767ca70ace9bb6aa01d120d81afca5e4ae384f1b3
13) session:3a6e4b311188ffe8bcb77395f4630a3195101f9b97fac4df92500d81a54bd9c3
14) session:1d8d895611124219fb6d4050bfd33f389c37c9372bed5914e41ece3076887764
15) session:8681199c186fbc29ab600a1e8279986e85863ed9a6cd59d0ef47d6968815ea36
16) session:1278a7b63f88716372f797fd018a635f081a78d35ce8137be15020abd88261b4
(... and so on...)
```

Any idea how this could be happening?

**Comment by axos88** [comment]
redis-rails (5.0.2)

**Comment by axos88** [comment]
https://github.com/redis-store/redis-rails/issues/87 This might be related, but I'm not sure what the OP means by "if it's included in the config"

**Comment by tubbo** [comment]
@axos88 if you're using the `redis-namespace` gem then it might be related. what version of redis-actionpack do you have installed? also, is this a rails 6 app?

**Comment by axos88** [comment]
I'm not:

```
akos$ cat Gemfile.lock | grep namespace
✘  00:43:20 ~/projects/ruby/heroku {ruby-2.5.1@heroku} [master → origin/master ↑·17|✔ ]
```

**Comment by axos88** [comment]
```
akos$ cat Gemfile.lock | grep actionpack
      actionpack (= 5.2.1)
      actionpack (= 5.2.1)
    actionpack (5.2.1)
      actionpack (= 5.2.1)
      actionpack (= 5.2.1)
      actionpack (= 5.2.1)
    redis-actionpack (5.0.2)
      actionpack (>= 4.0, < 6)
      redis-actionpack (>= 5.0, < 6)
      actionpack (>= 4.0)
```

It's a rails 5.2 app

**Comment by tubbo** [comment]
In that case, I don’t think this would be related, but maybe I’m wrong. Anyway I’ll try to reproduce and look into it.

**Comment by tubbo** [comment]
Sorry this kinda fell off my radar. I don't really believe the namespace is the problem here, actually, because our default server is `redis://127.0.0.1:6379/0/rack:session`. That's what we use for testing, and it has a namespace in it. Are you seeing all keys not get a TTL or just some?

**Comment by axos88** [comment]
Just some, that's the weird part.

**Comment by axos88** [comment]
Currently i have 18 keys in the database without TTLs. It's a low traffic site (actually I'm the only user), so probably all of those are stale.

**Comment by axos88** [comment]
I just logged in, and now I have 19 keys, with 1 set with a TTL, so the new key was created with a TTL / the TTL was added after creation

**Comment by axos88** [comment]
The key DOES look a bit different though:

```
1) session:5df27c4f16db9b93e767fcfbf27bec2cfd196859425b0bea703bea3759c820a4
2) session:69c7760cd0e7cb325b43a54136ab3b72f9e19935a8927b4704cac46386c528bc
3) session:73d995920e2cf8dddd8ffb16754b11ba12b28c68f1631417f74bde0908e7b760
4) session:ad5b0a27fb20a816ff346335aaf73b650f1726f78f63b8512d79bc33153068ea
5) session:3856f51e6a47436f1364ad728ca4b9e8800221416b7b160591690617cfe9ce6a
6) session:e8381b824bd794c404c0b626d2e074551a8cc4bc26e9b7747c1bcb68d0db2903
7) session:7d377f9ff15931a84b0d2fedfa0c7dd39dc252837681f2bc1f8672de3190bb42
8) session:30d83b6abfaf954e4cef31ed553fa415675553f8d5a83670780df9fb35b7de87
9) session:af5b60e9b2defe2304f2b4a7957345ce4dfe85aa5014c64752ad96c1207087d8
10) session:0016af0b9b531cb675f82831c222f6c664d5af2479a48488ac7ebac14949a8d2
11) session:611d96c1319897042d56689784a7771f
12) session:4431048ae9cde0d21359ed86703340b86a50056d9e621f3e5009961a7a1195a1
13) session:ea46dbf168750ff502947a422af5ce241af5944b23a7576fa55ec1ad9b6ea008
14) session:f2eb9368aa721fb050f746a67888a226260de168a63b10b62d2b24967df36a40
15) session:ce0486976cc5005800041d8947979a19212ca8212031a8b8e71dd7b73d19f320
16) session:561d8976be24702b7566cde73a5f668df50836fb8bb11b68e33ab8d6bcb5121b
17) session:56c6c6171cf487ba688202fbddda388fdb942c997fa7e9c49ca39d487735c07a
18) session:77a82d1f374c1c047d4414b7e6756c964361b8cf7c72a11f63fa65b8298c4d92
19) session:179cbae49664e68f04c14e8914edf88131e1e6a9d22864e7b2eba69cd54e562a
```

**Comment by tubbo** [comment]
@axos88 is it possible that you updated redis-rack at some point and that's what's making those sessions different?

**Comment by axos88** [comment]
I mean that's possible, but if I delete them, they come back, so something is STILL making those sessions

**Comment by axos88** [comment]
Seems like the bad sessions are coming from rack. I just upgraded to rack 2.1.2, and it started throwing exceptions, because it was getting a `Rack::Session::SessionId` instead of strings for writing to redis. I'll try to do a bundle update, and see what happens.

**Comment by axos88** [comment]
```
undefined method `match' for #<Rack::Session::SessionId:0x000055cef48c02a8>
```
redis-store (1.5.0) lib/redis/store/namespace.rb:98:in `interpolate'
redis-store (1.5.0) lib/redis/store/namespace.rb:89:in `namespace'
redis-store (1.5.0) lib/redis/store/namespace.rb:7:in `set'
redis-rack (2.0.4) lib/rack/session/redis.rb:61:in `block (2 levels) in set_session'
redis-rack (2.0.4) lib/rack/session/redis.rb:94:in `with'
redis-rack (2.0.4) lib/rack/session/redis.rb:61:in `block in set_session'
redis-rack (2.0.4) lib/rack/session/redis.rb:79:in `with_lock'
redis-rack (2.0.4) lib/rack/session/redis.rb:60:in `set_session'
rack (2.1.2) lib/rack/session/abstract/id.rb:508:in `write_session'
rack (2.1.2) lib/rack/session/abstract/id.rb:391:in `commit_session'
rack (2.1.2) lib/rack/session/abstract/id.rb:271:in `context'
rack (2.1.2) lib/rack/session/abstract/id.rb:263:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
bugsnag (6.11.1) lib/bugsnag/integrations/rack.rb:46:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.1.2) lib/rack/method_override.rb:24:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.2.1) lib/rails/engine.rb:524:in `call'
puma (4.3.0) lib/puma/configuration.rb:228:in `call'
puma (4.3.0) lib/puma/server.rb:667:in `handle_request'
puma (4.3.0) lib/puma/server.rb:470:in `process_client'
puma (4.3.0) lib/puma/server.rb:328:in `block in run'
puma (4.3.0) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by axos88** [comment]
Error went away, i'll delete the sessions, and see if they come back again. I'd hazard a guess that it was some old gem issue, time will tell.

**Comment by tubbo** [comment]
Feel free to re-open (or comment) if this is still a problem. Closing for now.

**Comment by axos88** [comment]
I can't reopen. Just checked again, I have 66 sessions in redis, only 11 have expiry set. And the hash lengths are now the same:


```
ec2-52-213-41-157.eu-west-1.compute.amazonaws.com:28549> ttl session:2::c79adf2fe6e39451a0639c694bc56cd3301ea13f76e4ca53cc7b3573a32dd05d
-1
ec2-52-213-41-157.eu-west-1.compute.amazonaws.com:28549> ttl session:2::d63e446a777722f950e261d5b68c4e1982d8e54e16e1b1bce69672dd986a6ffc
-1
ec2-52-213-41-157.eu-west-1.compute.amazonaws.com:28549> ttl session:2::595cf067bb9622946b482c5fb5f1dcc7aa87469ce4e11c4384f8afedd91a19ce
-1
ec2-52-213-41-157.eu-west-1.compute.amazonaws.com:28549> ttl session:2::b64aae9b80d9e4b9c3ad029bce37c96fae0cb8d138a882c3487d5de58c946950
-1
ec2-52-213-41-157.eu-west-1.compute.amazonaws.com:28549> ttl session:2::9181b316995b245c746c7b78e2aca1f8878f3f698cfa248c1bd8fc2dd2b1b215
4915

```

**Comment by tubbo** [comment]
You seem to be using an older version of `redis-rack` and possibly `redis-actionpack`, can you update those gems and see if it fixes anything?

**Comment by axos88** [comment]
I'm using rails 5.2. bundle update doesn't update anything, seems like I'm on the latest that's available for rails 5.2

**Comment by tubbo** [comment]
@axos88 since rails 5.0.0 was released, `redis-actionpack` has been compatible with every version of rails. https://github.com/redis-store/redis-actionpack/blob/master/redis-actionpack.gemspec#L23, so I think the dependency issue might be in `Gemfile`. Can you try explicitly running `bundle update redis-rack redis-actionpack`? If that doesn't update anything, there must be something in `Gemfile` preventing it from using the latest version. Only thing I can think of is the transition between Rack 2 and Rack 1. We are depending on Rack 2.x now in redis-actionpack due to some security issues that were not backwards compatible. Are you using Rack 2?

**Comment by axos88** [comment]
But I am using redis-actionpack 5.2.0, which seems to be latest.

```
GIT
  remote: https://github.com/axos88/sidekiq-enqueuer
  revision: d6970ad79a22b45557003543230d5bdc0d1f7f5b
  branch: marker-class
  specs:
    sidekiq-enqueuer (2.1.0)

GIT
  remote: https://github.com/axos88/sidekiq-status
  revision: 8c469c47cded772e8fd7a1cff5c23d147a3e9c8c
  branch: feature/show-custom-data-on-status-page
  specs:
    sidekiq-status (1.0.2)
      chronic_duration
      sidekiq (>= 3.0)

PATH
  remote: engines/acme
  specs:
    acme (0.1.0)
      acme-client (~> 2.0.5)
      rails (~> 5.2.1)

PATH
  remote: engines/airbnb
  specs:
    airbnb (0.1.0)
      aasm
      dropbox_api
      faye-websocket
      hash_diff
      rails (~> 5.2.1)
      selenium-webdriver

PATH
  remote: engines/fb_messenger
  specs:
    fb_messenger (0.1.0)
      facebook-messenger (~> 1.4.1)
      msgpack (~> 1.3.1)
      rails (~> 5.2.1)

PATH
  remote: engines/pushbullet
  specs:
    pushbullet (0.1.0)
      rails (~> 5.2.1)

PATH
  remote: engines/twilio
  specs:
    twilio (0.1.0)
      rails (~> 5.2.1)

GEM
  remote: https://rubygems.org/
  specs:
    aasm (5.0.6)
      concurrent-ruby (~> 1.0)
    acme-client (2.0.5)
      faraday (~> 0.9, >= 0.9.1)
    actioncable (5.2.4.1)
      actionpack (= 5.2.4.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.4.1)
      actionpack (= 5.2.4.1)
      actionview (= 5.2.4.1)
      activejob (= 5.2.4.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.4.1)
      actionview (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.4.1)
      activesupport (= 5.2.4.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.2.4.1)
      activesupport (= 5.2.4.1)
      globalid (>= 0.3.6)
    activemodel (5.2.4.1)
      activesupport (= 5.2.4.1)
    activerecord (5.2.4.1)
      activemodel (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      arel (>= 9.0)
    activestorage (5.2.4.1)
      actionpack (= 5.2.4.1)
      activerecord (= 5.2.4.1)
      marcel (~> 0.3.1)
    activesupport (5.2.4.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    after_commit_everywhere (0.1.4)
      activerecord (>= 4.2)
    arel (9.0.0)
    autoprefixer-rails (9.7.4)
      execjs
    benchmark-ips (2.7.2)
    bootstrap (4.1.3)
      autoprefixer-rails (>= 6.0.3)
      popper_js (>= 1.12.9, < 2)
      sass (>= 3.5.2)
    bootstrap_form (4.3.0)
      actionpack (>= 5.0)
      activemodel (>= 5.0)
    bugsnag (6.13.0)
      concurrent-ruby (~> 1.0)
    builder (3.2.4)
    byebug (11.1.1)
    childprocess (3.0.0)
    chronic_duration (0.10.6)
      numerizer (~> 0.1.1)
    coderay (1.1.2)
    coffee-rails (5.0.0)
      coffee-script (>= 2.2.0)
      railties (>= 5.2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    commit_param_routing (0.0.1)
    concurrent-ruby (1.1.5)
    connection_pool (2.2.2)
    countries (3.0.0)
      i18n_data (~> 0.8.0)
      sixarm_ruby_unaccent (~> 1.1)
      unicode_utils (~> 1.4)
    country_select (4.0.0)
      countries (~> 3.0)
      sort_alphabetical (~> 1.0)
    crass (1.0.6)
    declarative (0.0.10)
    declarative-option (0.1.0)
    derailed (0.1.0)
      derailed_benchmarks
    derailed_benchmarks (1.6.0)
      benchmark-ips (~> 2)
      get_process_mem (~> 0)
      heapy (~> 0)
      memory_profiler (~> 0)
      rack (>= 1)
      rake (> 10, < 14)
      ruby-statistics (>= 2.1)
      thor (>= 0.19, < 2)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.7.5)
    dotenv-rails (2.7.5)
      dotenv (= 2.7.5)
      railties (>= 3.2, < 6.1)
    dropbox_api (0.1.18)
      faraday (<= 1.0)
      oauth2 (~> 1.1)
    erubi (1.9.0)
    et-orbi (1.2.2)
      tzinfo
    eventmachine (1.2.7)
    execjs (2.7.0)
    facebook-messenger (1.4.1)
      httparty (~> 0.13, >= 0.13.7)
      rack (>= 1.4.5)
    faraday (0.17.3)
      multipart-post (>= 1.2, < 3)
    faraday-cookie_jar (0.0.6)
      faraday (>= 0.7.4)
      http-cookie (~> 1.0.0)
    faraday_middleware (0.14.0)
      faraday (>= 0.7.4, < 1.0)
    faye-websocket (0.10.9)
      eventmachine (>= 0.12.0)
      websocket-driver (>= 0.5.1)
    ffi (1.12.2)
    flipper (0.17.2)
    flipper-active_record (0.17.2)
      activerecord (>= 4.2, < 7)
      flipper (~> 0.17.2)
    flipper-ui (0.17.2)
      erubi (>= 1.0.0, < 2.0.0)
      flipper (~> 0.17.2)
      rack (>= 1.4, < 3)
      rack-protection (>= 1.5.3, < 2.1.0)
    font-awesome-rails (4.7.0.5)
      railties (>= 3.2, < 6.1)
    fugit (1.3.3)
      et-orbi (~> 1.1, >= 1.1.8)
      raabro (~> 1.1)
    get_process_mem (0.2.5)
      ffi (~> 1.0)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    google-api-client (0.36.4)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (~> 0.9)
      httpclient (>= 2.8.1, < 3.0)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
      signet (~> 0.12)
    google_drive (3.0.4)
      google-api-client (>= 0.11.0, < 0.37.0)
      googleauth (>= 0.5.0, < 1.0.0)
      nokogiri (>= 1.5.3, < 2.0.0)
    googleauth (0.10.0)
      faraday (~> 0.12)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (~> 0.12)
    hash_diff (1.0.0)
    hashie (3.5.7)
    heapy (0.1.4)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    httparty (0.17.3)
      mime-types (~> 3.0)
      multi_xml (>= 0.5.2)
    httpclient (2.8.3)
    i18n (1.8.2)
      concurrent-ruby (~> 1.0)
    i18n_data (0.8.0)
    jquery-rails (4.3.5)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jwt (2.2.1)
    loofah (2.4.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    memoist (0.16.2)
    memory_profiler (0.9.14)
    method_source (0.9.2)
    mime-types (3.3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2019.1009)
    mimemagic (0.3.4)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.14.0)
    msgpack (1.3.3)
    multi_json (1.14.1)
    multi_xml (0.6.0)
    multipart-post (2.1.1)
    nav_lynx (1.1.1)
      rails (>= 3.1.0)
    nio4r (2.5.2)
    nokogiri (1.10.7)
      mini_portile2 (~> 2.4.0)
    numerizer (0.1.1)
    oauth2 (1.4.3)
      faraday (>= 0.8, < 2.0)
      jwt (>= 1.0, < 3.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.6.1)
      hashie (>= 3.4.6, < 3.6.0)
      rack (>= 1.6.2, < 3)
    omniauth-auth0 (1.4.2)
      omniauth-oauth2 (~> 1.1)
    omniauth-oauth2 (1.5.0)
      oauth2 (~> 1.1)
      omniauth (~> 1.2)
    os (1.0.1)
    pdfkit (0.8.4.1)
    pg (0.21.0)
    popper_js (1.16.0)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-byebug (3.8.0)
      byebug (~> 11.0)
      pry (~> 0.10)
    public_suffix (4.0.3)
    puma (4.3.1)
      nio4r (~> 2.0)
    raabro (1.1.6)
    rack (2.1.2)
    rack-protection (2.0.8.1)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.4.1)
      actioncable (= 5.2.4.1)
      actionmailer (= 5.2.4.1)
      actionpack (= 5.2.4.1)
      actionview (= 5.2.4.1)
      activejob (= 5.2.4.1)
      activemodel (= 5.2.4.1)
      activerecord (= 5.2.4.1)
      activestorage (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      bundler (>= 1.3.0)
      railties (= 5.2.4.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    rails-i18n (5.1.3)
      i18n (>= 0.7, < 2)
      railties (>= 5.0, < 6)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.5)
    rails_stdout_logging (0.0.5)
    railties (5.2.4.1)
      actionpack (= 5.2.4.1)
      activesupport (= 5.2.4.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    rake (13.0.1)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rdoc (6.2.1)
    redis (4.1.3)
    redis-actionpack (5.2.0)
      actionpack (>= 5, < 7)
      redis-rack (>= 2.1.0, < 3)
      redis-store (>= 1.1.0, < 2)
    redis-activesupport (5.2.0)
      activesupport (>= 3, < 7)
      redis-store (>= 1.3, < 2)
    redis-rack (2.1.0)
      rack (>= 2.0.8, < 3)
      redis-store (>= 1.2, < 2)
    redis-rails (5.0.2)
      redis-actionpack (>= 5.0, < 6)
      redis-activesupport (>= 5.0, < 6)
      redis-store (>= 1.2, < 2)
    redis-store (1.8.1)
      redis (>= 4, < 5)
    representable (3.0.4)
      declarative (< 0.1.0)
      declarative-option (< 0.2.0)
      uber (< 0.2.0)
    retriable (3.1.2)
    ruby-statistics (2.1.1)
    rubyzip (2.2.0)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sassc (2.2.1)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    sdoc (1.0.0)
      rdoc (>= 5.0)
    selenium-webdriver (3.142.7)
      childprocess (>= 0.5, < 4.0)
      rubyzip (>= 1.2.2)
    sidekiq (6.0.4)
      connection_pool (>= 2.2.2)
      rack (>= 2.0.0)
      rack-protection (>= 2.0.0)
      redis (>= 4.1.0)
    sidekiq-cron (1.1.0)
      fugit (~> 1.1)
      sidekiq (>= 4.2.1)
    sidekiq-unique-jobs (6.0.18)
      concurrent-ruby (~> 1.0, >= 1.0.5)
      sidekiq (>= 4.0, < 7.0)
      thor (~> 0)
    signet (0.12.0)
      addressable (~> 2.3)
      faraday (~> 0.9)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    sixarm_ruby_unaccent (1.2.0)
    sort_alphabetical (1.1.0)
      unicode_utils (>= 1.2.2)
    spring (2.1.0)
    sprockets (4.0.0)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    state_machines (0.5.0)
    state_machines-activemodel (0.7.1)
      activemodel (>= 4.1)
      state_machines (>= 0.5.0)
    state_machines-activerecord (0.6.0)
      activerecord (>= 4.1)
      state_machines-activemodel (>= 0.5.0)
    thor (0.20.3)
    thread_safe (0.3.6)
    tilt (2.0.10)
    tzinfo (1.2.6)
      thread_safe (~> 0.1)
    uber (0.1.0)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.6)
    unicode_utils (1.4.0)
    websocket-driver (0.7.1)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.4)
    wkhtmltopdf-binary (0.12.5.1)
    wkhtmltopdf-heroku (2.12.5.0)

PLATFORMS
  ruby

DEPENDENCIES
  acme!
  after_commit_everywhere
  airbnb!
  bootstrap (~> 4.1.3)
  bootstrap_form (>= 4.0.0.alpha1)
  bugsnag (~> 6.11)
  coffee-rails
  commit_param_routing
  countries
  country_select (~> 4.0)
  derailed
  dotenv-rails
  faraday-cookie_jar
  faraday_middleware
  fb_messenger!
  flipper
  flipper-active_record
  flipper-ui
  font-awesome-rails
  google_drive
  jquery-rails
  nav_lynx
  omniauth (~> 1.6.0)
  omniauth-auth0 (~> 1.4.1)
  pdfkit
  pg (~> 0.18)
  pry-byebug
  puma
  pushbullet!
  rails
  rails-i18n (~> 5.1)
  rails_12factor
  redis-rails (~> 5.0)
  redis-store (~> 1.5)
  sassc-rails
  sdoc
  sidekiq
  sidekiq-cron
  sidekiq-enqueuer!
  sidekiq-status!
  sidekiq-unique-jobs
  spring
  state_machines-activerecord
  twilio!
  uglifier
  wkhtmltopdf-binary
  wkhtmltopdf-heroku (= 2.12.5.0)

RUBY VERSION
   ruby 2.7.0p0

BUNDLED WITH
   2.1.2
```

**Comment by tubbo** [comment]
ok, so that's a different version (redis-rack 2.1.0 vs 2.0.8) than what you showed me before...hence why i asked.

**Comment by tubbo** [comment]
latest version of redis-rack is 2.1.1... https://github.com/redis-store/redis-rack/releases/tag/v2.1.1

**Comment by axos88** [comment]
Must've been the upgrades i did in between, sorry. I'll update to 2.1.1 tomorrow and check again, although i'm not convinced it will make a difference.

**Comment by axos88** [comment]
As far as I see, there is a single comment between the two, and it has been reverted on master

**Comment by tubbo** [comment]
ahh shit, turns out I forgot to release it to RubyGems. Just release v2.1.2, which reverts the change that was causing this issue.

**Comment by axos88** [comment]
So you say that the issue was introduced by commit https://github.com/redis-store/redis-rack/commit/34286586e4a793411c8aefbdc211ba47764303ad, but the issue was present before that commit was ever made (this has been happening for at least 6 months now, but i reported it just now.

I'll update my gems tomorrow, and report back in a few days, maybe i didn't understand what is happening correctly.

**Comment by axos88** [comment]
Also my app is a single process, so i'm not sure if a race condition is actually possible

**Comment by tubbo** [comment]
Well, I say that because other people have had a similar symptom (sessions not clearing) and it was demonstrably introduced by that commit. In your case, if you say the problem has been happening for almost half a year, then I'm not sure what's going on. It could be a rogue process running an older version of `redis-rack`, or maybe even another application (like a staging server that everyone forgot about) that's writing to the same Redis server as the one in production.

**Comment by axos88** [comment]
No, i'm pretty confident it's not something that was left there, because it's deployed to heroku through a docker build, so everything should be fresh, and the redis instance only accepts connections from that host.

What I thought of yesterday is wether it's possible to have something to do with the sidekiq process that is started, perhaps that process is writing to the session data for some reason, although I'm not sure why it would.

Is there any way to configure the keys to look a bit differently, to change that, and see if the keys without ttl-s get renamed too? That way it would be possible to determine wether the session keys are coming from this "subsystem".

**Comment by tubbo** [comment]
I believe the session IDs are being set by `rack/session` itself, as `redis-rack` is just taking that generated SID and storing it in Redis. So, maybe? Not totally sure how you'd do that though.

**Comment by tubbo** [comment]
closing for inactivity, feel free to comment if it's still an issue...

**Comment by progmas** [comment]
you can try this.

`MyAPP::Application.config.session_store :redis_store, key: '_my_app_session',
  :expires_in => 20.minutes`
